### ISSUE TITLE
GridBroadphase Needs support for more than just planes and spheres.

### ISSUE THREAD

**Issue by robrohan** [TheRohans/dapao#2]
The class feels like it needs a bit of refactoring as well.

**Comment by swift502** [comment]
Maybe I'm wrong, but it seems to me that everything is supported by default, as all shapes implement `computeAABB`...

https://github.com/TheRohans/dapao/blob/5583c36c0120ff9d961cc3aa823716c7ca8142a5/src/collision/GridBroadphase.ts#L192-L206

Spheres and planes aren't the only ones supported, they're the special cases. I don't know why sphere is a special case (maybe optimization?), but plane doesn't seem to implement `computeAABB`. Even if it did, you wouldn't want to put a 45° angled plane into every bin, but only half of the bins beneath the surface.

Once all objects are put into bins, only bins with more than one objects have further computations done.

I haven't tested it, but the class seems fine to me, apart from the [`addBoxToBins`](https://github.com/TheRohans/dapao/blob/5583c36c0120ff9d961cc3aa823716c7ca8142a5/src/collision/GridBroadphase.ts#L114-L144) function, which is declared as a const for some reason..

**Comment by robrohan** [comment]
Awesome, thanks for looking forward into this.  I just made this issues while porting it over and didn’t read the whole class very well. 

The const is fine, but that creation of the closure could probably be moved out of that loop.  For another day maybe. 

I haven’t actually used this class yet, but if you want to use it as a quick sanity test we can close this.
