### ISSUE TITLE
Checkout CCD and see if it looks good

### ISSUE THREAD

**Issue by robrohan** [TheRohans/dapao#8]
https://github.com/schteppe/cannon.js/issues/366

CCD = [Continuous Collision Detection](http://www.stencyl.com/help/view/continuous-collision-detection/)

**Comment by swift502** [comment]
So CCD stands for... what?
I looked at the gifs but saw no difference.

**Comment by robrohan** [comment]
> So CCD stands for... what?
> I looked at the gifs but saw no difference.

Good point, updated  :)

**Comment by swift502** [comment]
Wow! That's really cool. I never realised that the so called "tunneling" problem had a solution...

**Comment by robrohan** [comment]
Too hard to merge at the moment.
